name=ESP-Config
version=1.1.0
author=Jim Heaney
maintainer=Jim Heaney <jim.heaney@mail.com>
sentence=Dynamically configure ESP32 projects from your computer with a simple interface.
paragraph=Creates an open-ended configuration interface for ESP32 projects. Allows a companion computer application to dynamically generate a UI for the user to configure settings, send commands, and view critical information. Password-protect crucial settings, and verify all settings are handled properly with built-in hash verification.
category=Communication
url=https://github.com/JimHeaney/ESP-Config
architectures=esp32
depends=ArduinoJson
